### ISSUE TITLE
TypeError: Cannot call method 'getTime' of null

### ISSUE THREAD

**Issue by kaihendry** [laktek/punch#107]
This change https://github.com/hackerspacesg/hackerspace.sg/commit/45034236fdd10e16671122504e0d857d2c12ab8f causes `punch g` to fail with:

```
/usr/lib/node_modules/punch/lib/asset_bundler.js:314
                    var bundle_fingerprint = stat.mtime.getTime();
                                                        ^
TypeError: Cannot call method 'getTime' of null
    at /usr/lib/node_modules/punch/lib/asset_bundler.js:314:40
    at traverse_bundled_files    (/usr/lib/node_modules/punch/lib/asset_bundler.js:247:13)
   at /usr/lib/node_modules/punch/lib/asset_bundler.js:236:15
   at /usr/lib/node_modules/punch/lib/template_handler.js:48:12
   at Object.oncomplete (fs.js:107:15)
```

**Comment by jperelli** [comment]
Confirmed what @laktek says. I had this error.

This was my config file
```
[....]
	"bundles": {
		"/css/all.css": [
			"/css/normalize.css",	
			"/css/main.css",
			"/css/site.less"
		]	
	}
```

The problem was that I deleted the files `css/normalize.css`, `css/main.css` and `css/site.less`.

I fixed this removing those from the config file, leaving it like this
```
[....]
	"bundles": {
	}
```
